### PR TITLE
New parameter to configure clustering without HA

### LINKED ISSUE #176: Support for clustered brokers
##### SUMMARY
Topology: 3 instances, clustered, all running on different machines.

With the current config, 

Sample `inventory.yaml`:
```
---
all:
  hosts:
    ip-11-0-1-001.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
      amq_broker_cluster_connections:
      - name: amq3
        value: tcp://ip-11-0-3-001.eu-west-2.compute.internal:61616
      - name: amq2
        value: tcp://ip-11-0-1-002.eu-west-2.compute.internal:61616
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-3-001.eu-west-2.compute.internal
        port: 61616
      - name: amq2
        scheme: tcp
        address: ip-11-0-1-002.eu-west-2.compute.internal
        port: 61616
    ip-11-0-1-002.eu-west-2.compute.internal:
      amq_broker_instance_name: amq2
      amq_broker_cluster_connections:
      - name: amq1
        value: tcp://ip-11-0-1-002.eu-west-2.compute.internal:61616
      - name: amq3
        value: tcp://ip-11-0-3-001.eu-west-2.compute.internal:61616
      amq_broker_connectors:
      - name: amq1
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-3-001.eu-west-2.compute.internal
        port: 61616
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-002.eu-west-2.compute.internal
        port: 61616
    ip-11-0-3-001.eu-west-2.compute.internal:
      amq_broker_instance_name: amq3
      amq_broker_cluster_connections:
        - name: amq1
          value: tcp://ip-11-0-1-002.eu-west-2.compute.internal:61616
        - name: amq2
          value: tcp://ip-11-0-3-001.eu-west-2.compute.internal:61616
      amq_broker_connectors:
        - name: amq1
          scheme: tcp
          address: ip-11-0-1-001.eu-west-2.compute.internal
          port: 61616
        - name: artemis
          scheme: tcp
          address: ip-11-0-3-001.eu-west-2.compute.internal
          port: 61616
        - name: amq2
          scheme: tcp
          address: ip-11-0-1-002.eu-west-2.compute.internal
          port: 61616
```

Sample `playbook.yaml`
```
---
- name: Deploy AMQ in 3 broker clustered setup
  hosts: all
  vars:
    ansible_ssh_private_key_file: my_keypair.pem
    amq_broker_ha_enabled: true
    amq_broker_nio_enabled: true
    amq_broker_cors_strict_checking: false
    amq_broker_prometheus_enabled: false
    amq_broker_cluster_discovery: "provided"
    amq_broker_addresses:
      - name: TEST
        anycast:
          - name: TEST
      - name: DLQ
        anycast:
          - name: DLQ
      - name: ExpiryQueue
        anycast:
          - name: ExpiryQueue
    amq_broker_acceptors:
      - name: artemis
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          amqpMinLargeMessageSize: 102400
          protocols: CORE
          useEpoll: true
          amqpCredits: 1000
          amqpLowCredits: 300
          amqpDuplicateDetection: true
          supportAdvisory: false
          suppressInternalManagementObjects: false
      - name: amqp
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port_amqp }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: AMQP
          useEpoll: true
          amqpMinLargeMessageSize: 102400
          amqpCredits: 1000
          amqpLowCredits: 300
          amqpDuplicateDetection: true
  roles:
    - redhat.amq_broker.amq_broker
```

The above produces 3 brokers but they container `ha-policy` which isn't what I want, as `amq_broker_ha_enabled` needs to be true, else you cant create any broker connections
- https://github.com/search?q=repo%3Aansible-middleware%2Famq%20-%20activemq_ha_enabled&type=code

### PR DESCRIPTION
**Pull request by guidograzioli**
Fix configuration for cluster topologies built with only primary servers. The ha-policy template failed to configure properly with `activemq_ha_enabled` and no backups; with no `activemq_ha_enabled` active, cluster-connections would not be generated.

New parameters:

| Variable | Description | Default |
|:---------|:------------|:--------|
|`activemq_cluster_enabled`| Whether or not to enable clustering (cluster-connections) | `{{ activemq_ha_enabled }}` |
|`activemq_scale_down_enabled` | Whether or not clustering supports scale-down" | `false` |

Fix  #176

### CODE REVIEW

**Comment by garethahealy** [comment]
I tested against the source but found one issue related to the new `activemq_cluster_enabled` flag.

The below doesn't have that flag, which means `activemq_cluster_nodes` is never populated when using `activemq_cluster_discovery=provided`
- https://github.com/guidograzioli/amq/blob/live_only_clustering/roles/activemq/tasks/main.yml#L28-L33

**Comment by guidograzioli** [comment]
> I tested against the source but found one issue related to the new `activemq_cluster_enabled` flag.
> 
> The below doesn't have that flag, which means `activemq_cluster_nodes` is never populated when using `activemq_cluster_discovery=provided`
> 
> * https://github.com/guidograzioli/amq/blob/live_only_clustering/roles/activemq/tasks/main.yml#L28-L33

OK i think it's complete now, thanks for the help. Can you review?

**Comment by garethahealy** [comment]
I've tested the latest. Got 3 clustered brokers, producing 600 messages to broker 1. Messages evenly (_200 each_) consumed by broker 1, 2 and 3

```
$ ansible-galaxy collection list | grep "middleware"
middleware_automation.amq     2.2.4
middleware_automation.common  1.2.2
```

**Pull request merged**
