### PR TITLE
Fix broker.xml connector and connector-ref when using federation

### LINKED ISSUE #177: Connectors cant be created for federated
##### SUMMARY
The issue is related to `activemq_ha_enabled` and `activemq_cluster_discovery`.

Federated isn't HA, nor is it Clustered. To get `connectors` created, I have to set activemq_ha_enabled=true and activemq_cluster_discovery=static or provided:
- https://github.com/ansible-middleware/amq/blob/5cc8e62337c00b4adc27033cd68b3e9324dc315c/roles/activemq/tasks/main.yml#L7-L33

But doing that will then create `cluster-connections`, which I don't want:
- https://github.com/ansible-middleware/amq/blob/5cc8e62337c00b4adc27033cd68b3e9324dc315c/roles/activemq/tasks/connectors.yml#L62-L74

If I don't set either flags, the broker starts up with federation created but not connectors.

If I set those flags, I get the below error when running the ansible playbook:

```
TASK [redhat.amq_broker.amq_broker : Create instance amq1 of amq_broker] **************************************************************************************************************************************************************************
[WARNING]: Module remote_tmp /opt/amq/apache-artemis-7.12.0/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as another user. To avoid this, create the remote_tmp dir with the correct
permissions manually
fatal: [ip-11-0-1-231.eu-west-2.compute.internal]: FAILED! => {"changed": true, "cmd": ["/opt/amq/amq-broker-7.12.0/bin/artemis", "create", "/opt/amq/amq1", "--name", "amq1", "--clustered", "--cluster-user", "amq-cluster-user", "--cluster-password", "amq-cluster-pass", "--max-hops", "1", "--message-load-balancing", "ON_DEMAND", "--failover-on-shutdown", "--staticCluster", "--require-login", "--user", "amq-broker", "--password", "amq-broker", "--host", "localhost", "--http-host", "0.0.0.0", "--http-port", "8161", "--no-autocreate", "--queues", "queue.in,queue.out", "--data", "/opt/amq/amq1/data", "--nio"], "delta": "0:00:01.228351", "end": "2024-09-24 09:31:03.340651", "msg": "non-zero return code", "rc": 1, "start": "2024-09-24 09:31:02.112300", "stderr": "Expected parameter for option '--static-cluster' but found '--require-login'", "stderr_lines": ["Expected parameter for option '--static-cluster' but found '--require-login'"], "stdout": "\nUsage: artemis help [<args>...]\nuse 'help <command>' for more information\n      [<args>...]", "stdout_lines": ["", "Usage: artemis help [<args>...]", "use 'help <command>' for more information", "      [<args>...]"]}

fatal: [ip-11-0-1-201.eu-west-2.compute.internal]: FAILED! => {"changed": true, "cmd": ["/opt/amq/amq-broker-7.12.0/bin/artemis", "create", "/opt/amq/amq2", "--name", "amq2", "--clustered", "--cluster-user", "amq-cluster-user", "--cluster-password", "amq-cluster-pass", "--max-hops", "1", "--message-load-balancing", "ON_DEMAND", "--failover-on-shutdown", "--staticCluster", "--require-login", "--user", "amq-broker", "--password", "amq-broker", "--host", "localhost", "--http-host", "0.0.0.0", "--http-port", "8161", "--no-autocreate", "--queues", "queue.in,queue.out", "--data", "/opt/amq/amq2/data", "--nio"], "delta": "0:00:01.304106", "end": "2024-09-24 09:31:03.466758", "msg": "non-zero return code", "rc": 1, "start": "2024-09-24 09:31:02.162652", "stderr": "Expected parameter for option '--static-cluster' but found '--require-login'", "stderr_lines": ["Expected parameter for option '--static-cluster' but found '--require-login'"], "stdout": "\nUsage: artemis help [<args>...]\nuse 'help <command>' for more information\n      [<args>...]", "stdout_lines": ["", "Usage: artemis help [<args>...]", "use 'help <command>' for more information", "      [<args>...]"]}
fatal: [ip-11-0-1-71.eu-west-2.compute.internal]: FAILED! => {"changed": true, "cmd": ["/opt/amq/amq-broker-7.12.0/bin/artemis", "create", "/opt/amq/amq3", "--name", "amq3", "--clustered", "--cluster-user", "amq-cluster-user", "--cluster-password", "amq-cluster-pass", "--max-hops", "1", "--message-load-balancing", "ON_DEMAND", "--failover-on-shutdown", "--staticCluster", "--require-login", "--user", "amq-broker", "--password", "amq-broker", "--host", "localhost", "--http-host", "0.0.0.0", "--http-port", "8161", "--no-autocreate", "--queues", "queue.in,queue.out", "--data", "/opt/amq/amq3/data", "--nio"], "delta": "0:00:01.643840", "end": "2024-09-24 09:31:03.850280", "msg": "non-zero return code", "rc": 1, "start": "2024-09-24 09:31:02.206440", "stderr": "Expected parameter for option '--static-cluster' but found '--require-login'", "stderr_lines": ["Expected parameter for option '--static-cluster' but found '--require-login'"], "stdout": "\nUsage: artemis help [<args>...]\nuse 'help <command>' for more information\n      [<args>...]", "stdout_lines": ["", "Usage: artemis help [<args>...]", "use 'help <command>' for more information", "      [<args>...]"]}
```

Sample inventory:
```
---
federated:
  hosts:
    ip-11-0-1-001.eu-west-2.compute.internal:
      amq_broker_instance_name: amq1
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq2
        scheme: tcp
        address: ip-11-0-1-002.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-1-003.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq1-federation
          upstreams:
            - name: amq2
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq2
            - name: amq3
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq3
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
    ip-11-0-1-002.eu-west-2.compute.internal:
      amq_broker_instance_name: amq2
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-002.eu-west-2.compute.internal
        port: 61616
      - name: amq1
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq3
        scheme: tcp
        address: ip-11-0-1-003.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq2-federation
          upstreams:
            - name: amq1
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq1
            - name: amq3
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq3
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
    ip-11-0-1-003.eu-west-2.compute.internal:
      amq_broker_instance_name: amq3
      amq_broker_connectors:
      - name: artemis
        scheme: tcp
        address: ip-11-0-1-003.eu-west-2.compute.internal
        port: 61616
      - name: amq1
        scheme: tcp
        address: ip-11-0-1-001.eu-west-2.compute.internal
        port: 61616
      - name: amq2
        scheme: tcp
        address: ip-11-0-1-002.eu-west-2.compute.internal
        port: 61616
      amq_broker_federations:
        - name: amq3-federation
          upstreams:
            - name: amq1
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq1
            - name: amq2
              user: amq-broker
              password: amq-broker
              static_connectors:
                - amq2
          queue_policies:
            - name: TEST
              includes:
                - queue_match: TEST
                  address_match: TEST
```

Sample playbook:
```
---
- name: Deploy AMQ in 3 broker federation setup
  hosts: federated
  vars:
    ansible_ssh_private_key_file: my_keypair.pem
    amq_broker_ha_enabled: true
    amq_broker_cluster_discovery: "provided"
    amq_broker_nio_enabled: true
    amq_broker_cors_strict_checking: false
    amq_broker_prometheus_enabled: false
    amq_broker_addresses:
      - name: TEST
        anycast:
          - name: TEST
      - name: DLQ
        anycast:
          - name: DLQ
      - name: ExpiryQueue
        anycast:
          - name: ExpiryQueue
    amq_broker_acceptors:
      - name: artemis
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          amqpMinLargeMessageSize: 102400
          protocols: CORE
          useEpoll: true
          amqpCredits: 1000
          amqpLowCredits: 300
          amqpDuplicateDetection: true
          supportAdvisory: false
          suppressInternalManagementObjects: false
      - name: amqp
        bind_address: "0.0.0.0"
        bind_port: "{{ amq_broker_port_amqp }}"
        parameters:
          tcpSendBufferSize: 1048576
          tcpReceiveBufferSize: 1048576
          protocols: AMQP
          useEpoll: true
          amqpMinLargeMessageSize: 102400
          amqpCredits: 1000
          amqpLowCredits: 300
          amqpDuplicateDetection: true
  roles:
    - redhat.amq_broker.amq_broker
```

### PR DESCRIPTION
**Pull request by guidograzioli**
Fix #177

### CODE REVIEW

**Comment by garethahealy** [comment]
check for the message `Connection configuration is null for connectorName` in the logs and I think you'll see this fail.

**Comment by guidograzioli** [comment]
> Connection configuration is null for connectorName

It was surrounded with double quotes, I committed the change removing them; also added a task to enforce <connectors> presence. Please give a look

**Comment by garethahealy** [comment]
Tested PR and works as expected

**Comment by guidograzioli** [comment]
> Tested PR and works as expected

Brilliant, thanks for all the help.

**Pull request merged**
